name: Bug Report
description: Report a bug or issue with platform infrastructure
title: "[BUG] "
labels: ["bug", "platform-team"]
assignees:
  - dcasati
body:
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical - Service Down
        - High - Major Functionality Impacted
        - Medium - Minor Functionality Impacted
        - Low - Cosmetic or Documentation
    validations:
      required: true
  
  - type: dropdown
    id: environment
    attributes:
      label: Affected Environment
      description: Which environment is affected?
      options:
        - Development
        - Staging
        - Production
        - All Environments
    validations:
      required: true
  
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Clear and concise description of the bug
      placeholder: What is the bug and what is the expected behavior?
    validations:
      required: true
  
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
  
  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Any relevant log output or error messages
      render: shell
  
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context about the problem